name: login to docker 
on:
  push:
    branches: ["main"]
jobs:
  login-to-docker-manually:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4
      - name: login 
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin
  
  login-to-docker-by-actions:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout-repo
        uses: action/checkout@v4
      - name: login by actions
        uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

